name: PR
on: pull_request
jobs:
  build:
    name: Verify PR
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go env
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-embdr
    - uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-go-embdr-target

    - name: Test
      run: make test

    - name: Lint
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make review

    - name: Build
      run: make build

    - name: Verify build
      run: make verify-no-changes

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: target/coverage.txt
